trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - fix/*

pr: none

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

jobs:
  - template: templates/jobs/default.yml@pipeline-library
    parameters:
      validationSteps:
        - script: |
            set -e
            zip auditd-config.zip ./config/*
          displayName: Package Bootstrap Scripts
