trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - fix/*

pr: none

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

jobs:
  - template: templates/jobs/default.yml@pipeline-library
    parameters:
      validationSteps:
        - script: |
            mkdir -p bootstrap
            rsync -a --prune-empty-dirs --include '*/' --include '*.sh' --include '*.ps1' --exclude '*' setup/ bootstrap/
            zip -r bootstrap-scripts.zip ./bootstrap
          displayName: Package Bootstrap Scripts
